Repository seoul-milk-team3/seoulmilk-frontend, pull requests merged in 2025-02, with the labels that each got.

#2 [Feat] 초기세팅
  .prettierrc
  eslint.config.js
  package.json
  pnpm-lock.yaml
  public/font/subset-PretendardVariable.woff2
  public/svg/ic_calender.svg
  public/vite.svg
  src/App.css
  src/App.tsx
  src/apis/index.tsx
  src/assets/images/index.tsx
  src/assets/react.svg
  src/assets/svg/IcCalender.tsx
  src/assets/svg/index.ts
  src/components/index.tsx
  src/constants/index.tsx
  src/custom.d.ts
  src/hooks/index.ts
  src/index.css
  src/main.tsx
  src/pages/index.tsx
  src/queryClient.ts
  src/routes/index.tsx
  src/styles/GlobalStyles.tsx
  src/styles/emotion.d.ts
  src/styles/reset.ts
  src/styles/theme.ts
  src/types/index.tsx
  src/utils/index.tsx
  tsconfig.app.json
  vite.config.ts
Labels: 🔧Setting, 🍀채원

#4 [Setting] 스토리북 초기 설정
  .github/workflows/chromatic.yml
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/provider.tsx
  package.json
  pnpm-lock.yaml
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/button.css
Labels: 🔧Setting, 🍀채원

#8 [Feat] text, flex 공통 컴포넌트
  .storybook/provider.tsx
  package.json
  pnpm-lock.yaml
  src/components/Flex/Flex.style.ts
  src/components/Flex/Flex.tsx
  src/components/Text/Text.style.ts
  src/components/Text/Text.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Flex.stories.tsx
  src/stories/Text.stories.tsx
  src/stories/button.css
  src/styles/theme.ts
  src/types/index.tsx
  src/types/textTyes.ts
  tsconfig.app.json
  vite.config.ts
Labels: ✨Feature, 🌻유민

#11 [Feat] 버튼 공통 컴포넌트
  src/components/Button/Button.style.ts
  src/components/Button/Button.tsx
  src/stories/Button.stories.tsx
  src/styles/theme.ts
Labels: ✨Feature, 🍀채원

#13 [Feat] 헤더, 모달 컴포넌트
  public/font/Seoulmilk_font.ttf
  public/svg/header_alarm.svg
  public/svg/header_dropdown.svg
  public/svg/seoulmilk_logo.svg
  public/svg/user_profile.svg
  src/assets/svg/HeaderAlarm.tsx
  src/assets/svg/HeaderDropdown.tsx
  src/assets/svg/SeoulmilkLogo.tsx
  src/assets/svg/UserProfile.tsx
  src/components/Header/Header.stories.tsx
  src/components/Header/Header.style.ts
  src/components/Header/Header.tsx
  src/components/Header/HeaderDropdown/HeaderDropdown.style.ts
  src/components/Header/HeaderDropdown/HeaderDropdown.tsx
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/Modal.style.ts
  src/components/Modal/Modal.tsx
  src/styles/GlobalStyles.tsx
Labels: ✨Feature, 🌻유민
