Repository seoul-milk-team3/seoulmilk-frontend, pull requests merged in 2025-03, with the labels that each got.

#27 #22 hotfix: 오류수정
  packages/ui/package.json
  pnpm-lock.yaml
Labels: 🔥Hotfix, 🍀채원

#36 [style]모바일 앱 캠 방향 전환&스타일 변경
  apps/agency/src/components/FileUpload/MobileCheckDone/MobileCheckDone.style.ts
  apps/agency/src/components/FileUpload/MobileCheckDone/MobileCheckDone.tsx
  apps/agency/src/components/FileUpload/MobileUploadSection/MobileUploadSection.style.ts
  apps/agency/src/components/FileUpload/MobileUploadSection/MobileUploadSection.tsx
  apps/agency/src/stories/MobileCheckDone.stories.tsx
  apps/agency/tsconfig.app.tsbuildinfo
Labels: 🎨Design, 🌻유민

#38 [로그인/회원가입] UI 구현
  .storybook/main.ts
  apps/agency/src/layouts/auth/AuthLayout.tsx
  apps/agency/src/layouts/main/MainLayout.style.ts
  apps/agency/src/pages/fileUpload/AgencyUploadPage.style.ts
  apps/agency/src/pages/fileUpload/AgencyUploadPage.tsx
  apps/agency/src/pages/login/LoginPage.style.ts
  apps/agency/src/pages/login/LoginPage.tsx
  apps/agency/src/pages/signUp/SignUpPage.style.ts
  apps/agency/src/pages/signUp/SignUpPage.tsx
  apps/agency/src/pages/signUp/components/SignupForm/SignupForm.style.ts
  apps/agency/src/pages/signUp/components/SignupForm/SignupForm.tsx
  apps/agency/src/routes/router.tsx
  apps/agency/tsconfig.app.tsbuildinfo
  apps/main/src/components/TabSwitch/TabSwitch.style.ts
  apps/main/src/components/TabSwitch/TabSwitch.tsx
  apps/main/src/layouts/auth/AuthLayout.tsx
  apps/main/src/layouts/main/MainLayout.style.ts
  apps/main/src/pages/fileUpload/MainUploadPage.style.ts
  apps/main/src/pages/fileUpload/MainUploadPage.tsx
  apps/main/src/pages/login/LoginPage.style.ts
  apps/main/src/pages/login/LoginPage.tsx
  apps/main/src/pages/signUp/SignUpPage.style.ts
  apps/main/src/pages/signUp/SignUpPage.tsx
  apps/main/src/pages/signUp/components/SignupForm/SignupForm.style.ts
  apps/main/src/pages/signUp/components/SignupForm/SignupForm.tsx
  apps/main/src/routes/router.tsx
  apps/main/src/stories/TabSwitch.stories.tsx
  apps/main/tsconfig.app.tsbuildinfo
  package.json
  packages/icon/assets/svg/ic_input_error.svg
  packages/icon/assets/svg/ic_login_logo.svg
  packages/icon/assets/svg/ic_pw_active.svg
  packages/icon/assets/svg/ic_pw_default.svg
  packages/icon/index.ts
  packages/icon/src/IcInputError.tsx
  packages/icon/src/IcLoginLogo.tsx
  packages/icon/src/IcPwActive.tsx
  packages/icon/src/IcPwDefault.tsx
  packages/ui/src/DropDown/Dropdown.style.ts
  packages/ui/src/DropDown/DropdownTrigger.tsx
  packages/ui/src/DropDown/SelectDropdown.tsx
  packages/ui/src/Input/Input.stories.tsx
  packages/ui/src/Input/Input.style.ts
  packages/ui/src/Input/Input.tsx
  packages/ui/src/index.ts
  pnpm-lock.yaml
Labels: ✨Feature, 🎨Design, 🍀채원

#42 [Feat] 자료조회 수정 UI, 상세보기 UI
  apps/main/src/constants/listData.ts
  apps/main/src/layouts/main/MainLayout.style.ts
  apps/main/src/pages/detail/DetailPage.style.ts
  apps/main/src/pages/detail/DetailPage.tsx
  apps/main/src/pages/detail/components/DetailItem/DetailItem.style.ts
  apps/main/src/pages/detail/components/DetailItem/DetailItem.tsx
  apps/main/src/pages/list/ListPage.tsx
  apps/main/src/pages/list/components/Filter/FilterContainer.style.ts
  apps/main/src/pages/list/components/Filter/FilterContainer.tsx
  apps/main/src/pages/list/components/ListContainer/ListContainer.tsx
  apps/main/src/pages/list/components/ListItem/ActionButton/ActionButton.tsx
  apps/main/src/pages/list/components/ListItem/ListItem.tsx
  apps/main/src/routes/router.tsx
  apps/main/src/types/index.ts
  apps/main/tsconfig.app.tsbuildinfo
  packages/icon/assets/svg/ic_check.svg
  packages/icon/assets/svg/ic_image_close.svg
  packages/icon/assets/svg/ic_image_zoom.svg
  packages/icon/index.ts
  packages/icon/src/IcCheck.tsx
  packages/icon/src/IcImageClose.tsx
  packages/icon/src/IcImageZoom.tsx
  packages/ui/src/CheckBox/CheckBox.stories.tsx
  packages/ui/src/CheckBox/CheckBox.style.ts
  packages/ui/src/CheckBox/CheckBox.tsx
  packages/ui/src/DropDown/Dropdown.style.ts
  packages/ui/src/DropDown/DropdownTrigger.tsx
  packages/ui/src/DropDown/SelectDropdown.stories.tsx
  packages/ui/src/DropDown/SelectDropdown.tsx
  packages/ui/src/Image/ImageModal/ImageModal.style.ts
  packages/ui/src/Image/ImageModal/ImageModal.tsx
  packages/ui/src/Image/ImagePreview/ImagePreview.stories.tsx
  packages/ui/src/Image/ImagePreview/ImagePreview.style.ts
  packages/ui/src/Image/ImagePreview/ImagePreview.tsx
  packages/ui/src/index.ts
Labels: ✨Feature, 🎨Design, 🚧Fix, 🍀채원

#57 [Feat] api 세팅 및 로그인 api 연결
  apps/agency/.env
  apps/agency/package.json
  apps/agency/src/routes/PrivateRoute.tsx
  apps/agency/src/routes/router.tsx
  apps/agency/tsconfig.app.tsbuildinfo
  apps/agency/vite.config.ts
  apps/main/.env
  apps/main/package.json
  apps/main/src/pages/login/LoginPage.tsx
  apps/main/src/routes/PrivateRoute.tsx
  apps/main/src/routes/router.tsx
  apps/main/tsconfig.app.tsbuildinfo
  package.json
  packages/api/.env
  packages/api/env.d.ts
  packages/api/package.json
  packages/api/src/HTTPError.ts
  packages/api/src/index.d.ts
  packages/api/src/index.ts
  packages/api/src/instance.ts
  packages/api/src/interceptor.ts
  packages/api/src/login/index.ts
  packages/api/src/login/queries.ts
  packages/api/src/login/types.ts
  packages/api/tsconfig.json
  packages/api/tsup.config.ts
  packages/ui/package.json
  packages/utils/package.json
  packages/utils/src/hooks/useOverlay.ts
  packages/utils/src/index.ts
  packages/utils/src/types/api.ts
  pnpm-lock.yaml
  tsconfig.json
Labels: ✨Feature, 🍀채원

#65 Fix/router
  .gitignore
  apps/agency/src/routes/router.tsx
  apps/main/src/routes/router.tsx
  packages/api/src/login/index.ts
Labels: 🔥Hotfix, 🚧Fix, 🍀채원

#67 [Feat] 회원가입&로그인 api 연동
  .gitignore
  apps/agency/.env
  apps/agency/src/pages/login/LoginPage.tsx
  apps/agency/src/pages/signUp/components/SignupForm/SignupForm.tsx
  apps/main/src/pages/signUp/components/SignupForm/SignupForm.tsx
  packages/api/src/index.ts
  packages/api/src/interceptor.ts
  packages/api/src/login/index.ts
  packages/api/src/login/queries.ts
  packages/api/src/login/types.ts
  packages/api/src/signup/index.ts
  packages/api/src/signup/queries.ts
  packages/api/src/signup/types.ts
  packages/ui/src/DropDown/DropdownRoot.tsx
Labels: ✨Feature, 🍀채원

#75 [Feat] 진위여부검증 api 연동 및 오류 수정
  apps/agency/.env
  apps/agency/.gitignore
  apps/main/.env
  apps/main/.gitignore
  apps/main/src/constants/authData.tsx
  apps/main/src/pages/authSelection/AuthSelectionPage.tsx
  apps/main/src/pages/confirm/ConfirmPage.tsx
  apps/main/src/pages/confrimAnalysis/ConfirmAnalysisPage.tsx
  apps/main/src/pages/confrimAnalysis/components/ConfirmResult/ConfirmResult.tsx
  apps/main/src/pages/erroList/ErrorListPage.tsx
  apps/main/src/pages/errorCheck/ErrorCheckPage.style.ts
  apps/main/src/pages/errorCheck/ErrorCheckPage.tsx
  apps/main/tsconfig.app.tsbuildinfo
  packages/api/.env
  packages/api/src/beforeValidationList/index.ts
  packages/api/src/beforeValidationList/queries.ts
  packages/api/src/beforeValidationList/types.ts
  packages/api/src/errorstore/queries.ts
  packages/api/src/index.ts
  packages/api/src/list/index.ts
  packages/api/src/list/queries.ts
  packages/api/src/list/types.ts
  packages/api/src/validation/index.ts
  packages/api/src/validation/queries.ts
  packages/api/src/validation/types.ts
Labels: ✨Feature, 🚧Fix, 🍀채원

#78 #73 fix: 필터링 오류 수정
  packages/api/src/list/index.ts
  packages/api/src/list/queries.ts
Labels: 🔥Hotfix, 🍀채원

#80 Feature/#76 agency
  apps/agency/src/constants/index.tsx
  apps/agency/src/pages/list/ListPage.style.ts
  apps/agency/src/pages/list/ListPage.tsx
  apps/agency/src/pages/list/components/Accordion/InvoiceDetails.style.ts
  apps/agency/src/pages/list/components/Accordion/InvoiceDetails.tsx
  apps/agency/src/pages/list/components/Accordion/InvoiceItem.style.ts
  apps/agency/src/pages/list/components/Accordion/InvoiceItem.tsx
  apps/agency/src/pages/list/components/FilterHeader/FilterHeader.style.ts
  apps/agency/src/pages/list/components/FilterHeader/FilterHeader.tsx
  apps/agency/src/pages/list/components/FilterHeader/StatusFilter.style.ts
  apps/agency/src/pages/list/components/FilterHeader/StatusFilter.tsx
  apps/agency/src/pages/list/components/StatusChip/StatusChip.style.ts
  apps/agency/src/pages/list/components/StatusChip/StatusChip.tsx
  apps/main/src/pages/confirm/ConfirmPage.tsx
  apps/main/src/pages/detail/DetailPage.tsx
  packages/api/src/agencyDetail/index.ts
  packages/api/src/agencyDetail/queries.ts
  packages/api/src/agencyDetail/types.ts
  packages/api/src/agencyList/index.ts
  packages/api/src/agencyList/queries.ts
  packages/api/src/agencyList/types.ts
  packages/api/src/index.ts
  packages/api/src/listDetail/types.ts
  packages/icon/assets/svg/ic_agency_arrow.svg
  packages/icon/index.ts
  packages/icon/src/IcAgencyArrow.tsx
  packages/ui/src/DropDown/SelectDropdown.tsx
  packages/ui/src/Image/ImagePreview/ImagePreview.tsx
  packages/ui/src/Pagination/Pagination.tsx
Labels: ✨Feature, 🍀채원
